name: Dialyzer

on: [push, pull_request]

steps:
  - uses: actions/checkout@v4
  - name: Set up Elixir
    id: beam
    uses: erlef/setup-beam@v1
    with:
      otp-version: 27
      elixir-version: 1.17

  - name: Restore PLT cache
    id: plt_cache
    uses: actions/cache/restore@v4
    with:
      key: |
        plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
      restore-keys: |
        plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
      path: |
        priv/plts

  - name: Create PLTs
    if: steps.plt_cache.outputs.cache-hit != 'true'
    run: mix dialyzer --plt

  - name: Save PLT cache
    id: plt_cache_save
    uses: actions/cache/save@v4
    if: steps.plt_cache.outputs.cache-hit != 'true'
    with:
      key: |
        plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
      path: |
        priv/plts

  - name: Run dialyzer
    run: mix dialyzer --format github --format dialyxir
